### PR TITLE
(GH-30) Fix infinite loop in script

### LINKED ISSUE #30: view-in-grafana has no timeout or error catching while waiting for grafana
**Steps to reproduce**

1. Ensure that localhost fails to resolve to the local address 127.0.0.1, for instance by removing `localhost` from `/etc/hosts`
2. Run `./view-in-grafana.sh <METRICS PATH>`

**Expected result**

The script fails at the `Waiting for graphite to be ready...` step with an error after a certain timeout.

**Observed result**

The script hangs at the `Waiting for graphite to be ready...` step indefinitely.

In the above example, `view-in-grafana.sh` L41-45 is a perpetual loop. Trying to break out of it also causes the rest of the script to execute with no service to connect to.

```
echo "Waiting for graphite to be ready..."
until nc -zv localhost 2003 >/dev/null 2>&1; do
  sleep 1
done
echo "ready"
```

`nc` doesn't and won't ever run in this scenario:

```
# nc -zv localhost 2003
nc: getaddrinfo: nodename nor servname provided, or not known
```

**Suggested changes**

The script should probably

- use 127.0.0.1 instead of localhost, or use an optional parameter to set the address
- timeout after a certain number of attempts
- emit or optionally log command output instead of piping it to /dev/null

### PR DESCRIPTION
**Pull request by jarretlavallee**
Prior to this commit, if the `nc` command in `view-in-grafana.sh` was unable
to access the database it would try indefinitely. Since we trapped the
ctrl-c it was a pain to stop the process. This commit adds a 60-second timeout to
the loop and will fail out if it is unable to connect.

Resolves #30

### CODE REVIEW

**Comment by jarretlavallee** [comment]
Updated with @m0dular's changes.

**Comment by jarretlavallee** [comment]
@gguillotte Can you test this and verify it solves #30?

**Comment by gguillotte** [comment]
Reviewing today; cannot merge: "Merging is blocked. The base branch restricts merging to authorized users."

**Comment by jarretlavallee** [comment]
Thanks @gguillotte. I can merge this if it looks good to you. Do you have permissions to do a  review?

**Review by gguillotte — APPROVED** [review]

**Pull request merged**
