### PR TITLE
Fix 400 return codes when borrowed-instances is null

### PR DESCRIPTION
**Pull request by m0dular**

### CODE REVIEW

**Comment by jarretlavallee** [comment]
Travis is not doing well today. I just kicked it to see if it will run.

**Comment by suckatrash** [comment]
I think the tests are broken because the grafana container uses alpine as a base image now.  So apt-get isn't available?
https://github.com/grafana/grafana/pull/18468

**Comment by jarretlavallee** [comment]
Good call @suckatrash. I think we can actually remove this as we no longer need this image in the master branch.

**Comment by jarretlavallee** [comment]
@m0dular After #35 is merged, let's rebase and this should be good to go

**Pull request merged**
