### PR TITLE
(maint) remove json2graphite.rb and download json2timeseriesdb

### PR DESCRIPTION
**Pull request by tkishel**
These files are (almost) duplicates.

"There can be only one" is the belief and motto among the immortals in the original Highlander film, its sequels and spin-offs. It implies that all immortals must fight and kill one another until only one remains standing; this "one" shall receive The Prize.

### CODE REVIEW

**Review by jarretlavallee — APPROVED** [review]
Looks good to me.

**Comment by tkishel** [comment]
Merge? :)

**Comment by RandellP** [comment]
Has to be @jarretlavallee ... I don't have permission to merge.

**Comment by jarretlavallee** [comment]
Merged!

**Comment by jarretlavallee** [comment]
@RandellP Permissions have been updated so you can merge in this repo now.

**Pull request merged**
